version: '3.8'

services:
  app:
    build: .
    container_name: api_restfull_laravel_app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - DB_HOST=db
      - DB_DATABASE=restaurante_apirestful
      - DB_USERNAME=usuario
      - DB_PASSWORD=contraseña

  db:
    image: mysql:8.0
    container_name: api_restfull_laravel_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: contraseña
      MYSQL_DATABASE: restaurante_apirestful
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contraseña
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
